config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: "users/confirmations"
  }

  root "pages#home"

  namespace :forum do
    resources :categories, only: %i[index create update destroy show] do
      collection do
        post :index
      end
      resources :topics, only: %i[create destroy]
    end

    resources :topics do
      patch :update_pinned, on: :member
      resources :posts, only: %i[create edit update destroy]
    end

    resources :tags, only: %i[index]
  end

  resource :profile, only: %i[show edit update], controller: "users/profiles" do
    collection do
      get :change_password, action: :edit_password
      patch :update_password
      delete :soft_delete
    end
  end
  resources :users, only: %i[show], controller: "users/profiles"

  get "about", to: "pages#about"
  get "faq", to: "pages#faq"
  get "privacy-policy", to: "pages#privacy_policy"
  get "up" => "rails/health#show", as: :rails_health_check

  get "/robots.txt" => "robots#show", defaults: { format: "txt" }

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
end

app/models/forum.rb
module Forum
  def self.table_name_prefix
    "forum_"
  end
end

app/models/forum/category.rb
# == Schema Information
#
# Table name: forum_categories
#
#  id           :integer          not null, primary key
#  bg_color     :string           not null
#  name         :string           not null
#  slug         :string           not null
#  topics_count :integer          default(0)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_forum_categories_on_slug  (slug) UNIQUE
#

class Forum::Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :topics, dependent: :nullify

  validates :name, presence: true, uniqueness: true
  validates :bg_color, presence: true, format: {
    with: /\A#(?:[0-9a-fA-F]{3}){1,2}\z/,
    message: "must be a valid hex color code (e.g. #FFF or #FFFFFF)"
  }

  private

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/models/forum/post.rb
# == Schema Information
#
# Table name: forum_posts
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  topic_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_forum_posts_on_topic_id  (topic_id)
#  index_forum_posts_on_user_id   (user_id)
#
# Foreign Keys
#
#  topic_id  (topic_id => forum_topics.id)
#  user_id   (user_id => users.id)
#

class Forum::Post < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :topic, counter_cache: true

  validates :content, presence: true

  after_commit :update_topic_active_at, on: %i[create update]

  private

  def update_topic_active_at
    topic.update_column(:active_at, updated_at)
  end
end

app/models/forum/tag.rb
# == Schema Information
#
# Table name: forum_tags
#
#  id           :integer          not null, primary key
#  name         :string           not null
#  slug         :string           not null
#  topics_count :integer          default(0), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_forum_tags_on_slug          (slug) UNIQUE
#  index_forum_tags_on_topics_count  (topics_count)
#

module Forum
  class Tag < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :taggables, dependent: :destroy
    has_many :topics, through: :taggables

    validates :name, presence: true, uniqueness: true

    private

    def should_generate_new_friendly_id?
      name_changed?
    end

    def self.ransackable_attributes(auth_object = nil)
      [ "name", "slug", "topics_count" ]
    end

    def self.ransackable_associations(auth_object = nil)
      [ "taggables", "topics" ]
    end
  end
end

app/models/forum/taggable.rb
# == Schema Information
#
# Table name: forum_taggables
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tag_id     :bigint           not null
#  topic_id   :bigint           not null
#
# Indexes
#
#  index_forum_taggables_on_tag_id    (tag_id)
#  index_forum_taggables_on_topic_id  (topic_id)
#
# Foreign Keys
#
#  tag_id    (tag_id => forum_tags.id)
#  topic_id  (topic_id => forum_topics.id)
#

class Forum::Taggable < ApplicationRecord
  belongs_to :topic, counter_cache: :tags_count
  belongs_to :tag, counter_cache: :topics_count
end

app/models/forum/topic.rb
# == Schema Information
#
# Table name: forum_topics
#
#  id          :integer          not null, primary key
#  active_at   :datetime         not null
#  content     :text             not null
#  num_views   :integer          default(0)
#  pinned_at   :datetime
#  posts_count :integer          default(0), not null
#  slug        :string           not null
#  tags_count  :integer          default(0), not null
#  title       :string(255)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_forum_topics_on_active_at    (active_at)
#  index_forum_topics_on_category_id  (category_id)
#  index_forum_topics_on_posts_count  (posts_count)
#  index_forum_topics_on_slug         (slug) UNIQUE
#  index_forum_topics_on_tags_count   (tags_count)
#  index_forum_topics_on_user_id      (user_id)
#
# Foreign Keys
#
#  category_id  (category_id => forum_categories.id)
#  user_id      (user_id => users.id)
#

class Forum::Topic < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user, counter_cache: true
  belongs_to :category, counter_cache: true
  has_many :taggables, dependent: :destroy
  has_many :tags, through: :taggables
  has_many :posts, dependent: :destroy

  validates :title, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :content, presence: true
  validates :category, presence: true

  validate :validate_maximum_tags_per_topic

  after_commit :update_active_at, on: %i[create update]

  def pinned?
    pinned_at.present?
  end

  def pin!
    update!(pinned_at: Time.current)
  end

  def unpin!
    update!(pinned_at: nil)
  end

  def participants
    User.where(id: [ user_id ] + posts.pluck(:user_id))
  end

  private

  def should_generate_new_friendly_id?
    title_changed?
  end

  def update_active_at
    update_column(:active_at, updated_at)
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[title category_id num_views posts_count active_at created_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[category posts user]
  end

  private

  def validate_maximum_tags_per_topic
    if tags_count > 5
      errors.add(:base, "A topic can have at most 5 tags")
    end
  end
end

app/controllers/forum/categories_controller.rb
module Forum
  class CategoriesController < ApplicationController
    def index
      @pagy, @categories = pagy(Category.order(name: :asc), limit: 6)

      @select_default_item = Shared::CustomSelectComponent::Item.new("", "Categories")
      @select_items = Category.all.map { |category| Shared::CustomSelectComponent::Item.new(category.slug, category.name, category.bg_color) }
      @category = Category.friendly.find_by(slug: params[:category]) if params[:category].present?

      set_meta_tags(
        title: "Categories",
        description: "Browse all discussion categories in our community forum",
        keywords: "categories, forum, discussion, community",
        canonical: forum_categories_url
      )
    end
  end
end

app/controllers/forum/posts_controller.rb
module Forum
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: %i[edit update destroy]
    before_action :authorize_access!, only: %i[edit update destroy]

    invisible_captcha only: [ :create ], on_spam: :redirect_spammer

    def create
      Forum::PostService.create_post!(
        user_id: current_user.id,
        topic_id: post_params[:topic_id],
        content: post_params[:content]
      )

      redirect_to forum_topic_path(post_params[:topic_id])
    end

    def edit
      @topic = @post.topic
    end

    def update
      Forum::PostService.update_post!(
        post_id: @post.id,
        content: post_params[:content]
      )

      redirect_to forum_topic_path(@post.topic_id), notice: "Post updated successfully."
    end

    def destroy
      Forum::PostService.delete_post!(post_id: @post.id)

      redirect_to forum_topic_path(@post.topic_id), notice: "Post deleted successfully."
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:forum_post).permit(:topic_id, :content)
    end

    def authorize_access!
      authorize @post
    end
  end
end

app/controllers/forum/tags_controller.rb
module Forum
  class TagsController < ApplicationController
    def index
      @q = Tag.ransack(params[:q])
      @pagy, @tags = pagy(@q.result, limit: 60)

      set_meta_tags(
        title: "Tags",
        description: "Browse all discussion topics by tags in our community forum",
        keywords: "tags, topics, forum, discussion, community,  discuss²",
        canonical: forum_tags_url
      )
    end
  end
end

app/controllers/forum/topics_controller.rb
module Forum
  class TopicsController < ApplicationController
    include MarkdownSanitazable

    before_action :authenticate_user!, only: %i[new create edit update update_pinned destroy]
    before_action :set_topic, only: %i[edit update update_pinned show destroy]
    before_action :authorize_access!, only: %i[edit update update_pinned destroy]
    before_action :set_custom_select_items, only: %i[new edit create update]

    invisible_captcha only: [ :create ], on_spam: :redirect_spammer

    def index
      @category = Category.friendly.find_by(slug: params[:category])

      @q = Topic.ransack(ransack_params)

      @pagy, @topics = pagy_countless(
        TopicFinder.perform(ransack_params: ransack_params, params: params),
        params: { q: ransack_params, category: params[:category], tag: params[:tag] }
      )

      @selected_category_slug = @category&.slug

      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end

    def show
      @posts = @topic.posts.includes(:user).order(created_at: :asc)
      @topic_tags = @topic.tags
      @topic.increment!(:num_views)
      @post = Post.new

      meta_description = sanitize_markdown(@topic.content)

      set_meta_tags(
        title: @topic.title,
        description: meta_description,
        keywords: "#{@topic.category.name}, #{@topic_tags.pluck(:name).join(', ')}, discussion,  discuss²",
        type: "article",
        canonical: forum_topic_url(@topic)
      )
    end

    def new
      @topic = Topic.new
    end

    def edit
      @selected_category_id = @topic.category_id
    end

    def create
      @topic = TopicService.create_topic!(
        user_id: current_user.id,
        category_id: topic_params[:category_id],
        tag_ids: topic_params[:tag_ids],
        title: topic_params[:title],
        content: topic_params[:content]
      )

      if @topic.persisted?
        redirect_to forum_topic_path(@topic), notice: "Topic was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      @topic = TopicService.update_topic!(
        user_id: current_user.id,
        category_id: topic_params[:category_id],
        tag_ids: topic_params[:tag_ids],
        topic_id: @topic.id,
        title: topic_params[:title],
        content: topic_params[:content]
      )

      if @topic.valid?
        redirect_to forum_topic_path(@topic), notice: "Topic was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def update_pinned
      if params[:pin] == "true"
        @topic.pin!
        redirect_to forum_topic_path(@topic), notice: "Topic pinned successfully."
      else
        @topic.unpin!
        redirect_to forum_topic_path(@topic), notice: "Topic unpinned successfully."
      end
    end

    def destroy
      TopicService.delete_topic!(topic_id: @topic.id)

      respond_to do |format|
        format.html { redirect_to forum_topics_path, notice: "Topic was successfully deleted." }
        format.turbo_stream do
          flash[:notice] = "Topic was successfully deleted."
          render turbo_stream: turbo_stream.action(:redirect, forum_topics_path)
        end
      end
    end

    private

    def set_topic
      @topic = Topic.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to forum_topics_path, alert: "Topic not found."
    end

    def set_custom_select_items
      @select_default_item = Shared::CustomSelectComponent::Item.new("", "Please select")
      @select_items = [ @select_default_item ] + Category.all.map do |category|
        Shared::CustomSelectComponent::Item.new(category.id, category.name, category.bg_color)
      end
    end

    def topic_params
      params.require(:forum_topic).permit(:category_id, :title, :content, tag_ids: [])
    end

    def ransack_params
      @ransack_params ||=
        params.fetch(:q, {}).permit(:category_id_eq, :title_cont, :s).tap do |whitelisted|
          whitelisted[:category_id_eq] = @category.id if @category.present?
        end
    end

    def authorize_access!
      authorize @topic
    end
  end
end

app/views/forum/topics/_topic.html.slim
- row_classes = topic.pinned? ? "bg-emerald-50 dark:bg-gray-700 border-b dark:border-gray-600" : "bg-white dark:bg-gray-800 border-b dark:border-gray-700"

tr id=dom_id(topic) class=row_classes
  th class="px-6 py-4 font-medium text-gray-900 dark:text-gray-100 whitespace-nowrap"
    div class="inline-flex items-baseline space-x-1"
      - if topic.pinned?
        span class="text-sm align-baseline material-icons dark:text-gray-200" push_pin
      = link_to topic.title.truncate(80), forum_topic_path(topic), data: { turbo: false }, class: "hover:underline dark:text-gray-200"
    br
    div class="text-xs text-gray-500 dark:text-gray-400 flex flex-col lg:flex-row items-start lg:items-center space-x-2 w-4/10"
      div class="flex flex-row items-center space-x-1"
        div style="width: 12px; height: 12px; background-color: #{topic.category.bg_color};"
        div = link_to topic.category.name, forum_topics_path(category: topic.category.slug), data: { turbo: false }, class: "hover:underline dark:text-gray-300"
      - if topic.tags.any?
        div class="ml-2 flex flex-wrap text-[11px]"
          - topic.tags.each_with_index do |tag, index|
            span
              = link_to tag.name, forum_topics_path(tag: tag.slug), data: { turbo: false }, class: "text-sky-600 dark:text-sky-400 hover:underline"
              - if index < topic.tags.size - 1
                span class="text-gray-500 dark:text-gray-400 mr-1" ,
  td class="px-6 py-4 dark:text-gray-300 w-1/5" = render Topics::AvatarsStackComponent.new(users_arr: topic.participants.limit(5))
  td class="px-6 py-4 dark:text-gray-300 w-1/10" = topic.posts_count
  td class="px-6 py-4 dark:text-gray-300 w-1/10" = topic.num_views
  td class="px-6 py-4 dark:text-gray-300 w-1/5" = "#{time_ago_in_words(topic.active_at)} ago"

app/views/forum/topics/_topic_form.html.slim
div class="form-container dark:bg-gray-800 p-6 shadow-md border dark:border-gray-700 w-full max-w-3xl mx-auto" role="main" aria-label="Topic form"
  = render "shared/error_messages", resource: @topic
  = form_with model: @topic, method: form_method, local: true, "aria-label" => "Create or edit topic" do |f|
    = invisible_captcha
    div class="mb-4"
      - category_items = Shared::CustomSelectComponent.category_items(slug_or_id: :id)
      = render Shared::CustomSelectComponent.new(label: "Select Category:*", form_name: "forum_topic[category_id]", items: category_items[:items], default_item: category_items[:default_item], auto_submit: false, selected_slug_or_id: @selected_category_id, arrow_icon: "keyboard_arrow_down", open_arrow_icon: "keyboard_arrow_up")
    div class="mb-4"
      = f.label :tag_ids, "Select Tags (Max 5):", class: "block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
      = f.select :tag_ids, Forum::Tag.pluck(:name, :id), {}, { multiple: true, data: { controller: 'slim-select' }, "aria-label" => "Select up to 5 tags for this topic" }
    div class="mb-4"
      = f.label :title, 'Title*', class: 'block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1'
      = f.text_field :title, class: 'block w-full border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-200 shadow-sm focus:ring-sky-600 focus:border-sky-600', required: true, "aria-required" => "true", "aria-describedby" => "title-help"
    div class="mb-4"
      = f.label :content, 'Content*', class: 'block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1'
      = f.text_area :content, class: 'block w-full border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-200 shadow-sm focus:ring-sky-600 focus:border-sky-600', rows: 6, required: true, "aria-required" => "true", "aria-describedby" => "content-help"
      span class="text-xs dark:text-gray-400" id="content-help" role="note"
        b class="dark:text-gray-300" Note: 
        | You can format content using 
        = link_to "markdown", "https://daringfireball.net/projects/markdown/syntax", target: "_blank", rel: "noopener noreferrer", class: "font-medium hover:underline dark:text-sky-400", "aria-label" => "Learn about Markdown formatting syntax (opens in new tab)"
        |  format.
    div class="flex justify-between mt-6"
      = f.button :submit, class: 'inline-flex items-center btn btn-primary', "aria-label" => "Submit topic" do
        span = button_text
      - if @topic.persisted?
        = link_to forum_topic_path(@topic), class: 'btn btn-light-gray', "aria-label" => "Go back to topic" do
          span Back to topic
      - else
        = link_to forum_topics_path, class: 'btn btn-light-gray', "aria-label" => "Go back to homepage" do
          span Back to homepage

app/views/forum/topics/edit.html.slim
div class="container mx-auto p-6"
  h3 class="text-center mb-4"
    |> Edit the topic:
    span class="font-bold" 
      = @topic.title.truncate(35)
    |< below
  = render 'forum/topics/topic_form', form_method: :patch, button_text: 'Update'

app/views/forum/topics/index.html.slim
div class="p-6" role="main" aria-label="Forum topics page"
  div class="flex flex-col space-y-4 lg:space-y-0 lg:flex-row lg:items-center lg:justify-between mb-4 mt-6"
    div class="flex flex-col space-y-4 md:space-y-0 md:flex-row md:gap-4" role="search" aria-label="Topic filters and search"
      = form_with url: forum_topics_path, method: :get, local: true, class: "flex items-center md:w-auto", "aria-label" => "Filter topics by category" do
        - category_items = Shared::CustomSelectComponent.category_items(default_label: "Categories")
        = render Shared::CustomSelectComponent.new(aria_label: "Filter by categories:", form_name: :category, items: category_items[:items], default_item: category_items[:default_item], auto_submit: true, selected_slug_or_id: @selected_category_slug, show_remove_filter: true, css_width: "w-3/5 md:w-56")
      = search_form_for @q, data: { turbo_frame: :results, controller: "search" }, class: "flex items-center flex-grow w-3/5", "aria-label" => "Search topics" do |f|
        = f.hidden_field :category_id_eq, value: @selected_category_id
        = f.search_field :title_cont, class: "border-gray-300 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-200 shadow-sm px-4 py-2 w-full focus:outline-none focus:ring-sky-600 focus:border-sky-600", \
            data: { action: "input->search#performSearch"}, \
            placeholder: "Search topics...", \
            autocomplete: "off", \
            "aria-label" => "Search topics by title"
      div class="flex justify-start space-x-4 md:space-x-6" role="navigation" aria-label="Sort options"
        = link_to "Latest", forum_topics_path(q: { s: "created_at desc" }, category: params[:category] ), class: "px-4 py-2 font-medium #{(params.dig(:q, :s) == 'created_at desc' || params.dig(:q, :s).blank?) ? 'text-sky-600 dark:text-sky-400 border-b-2 border-sky-600 dark:border-sky-400' : 'text-sky-600 dark:text-sky-400 hover:text-sky-700 dark:hover:text-sky-300'}", "aria-label" => "Sort topics by latest"
        = link_to "Top", forum_topics_path(q: { s: "posts_count desc" }, category: params[:category] ), class: "px-4 py-2 font-medium #{params.dig(:q, :s) == 'posts_count desc' ? 'text-sky-600 dark:text-sky-400 border-b-2 border-sky-600 dark:border-sky-400' : 'text-sky-600 dark:text-sky-400 hover:text-sky-700 dark:hover:text-sky-300'}", "aria-label" => "Sort topics by most replies"
        = link_to "Categories", forum_categories_path, class: "px-4 py-2 font-medium text-sky-600 dark:text-sky-400 hover:text-sky-700 dark:hover:text-sky-300", "aria-label" => "View all categories"
    - if current_user
      div class="flex justify-start mt-4 lg:mt-0"
        = link_to new_forum_topic_path, class: "btn btn-light-gray pl-2 w-auto", "aria-label" => "Create new topic" do
          span.material-icons add
          span New Topic
  div class="relative overflow-x-auto"
    = turbo_frame_tag :results do
      - if @topics.any?
        table class="w-full text-sm text-left text-gray-500 dark:text-gray-300" role="table" aria-label="Topics list"
          thead class="text-xs text-gray-700 dark:text-gray-300 border-b-8 dark:border-gray-700"
            tr role="row"
              th class="px-6 py-3" scope="col" Topic
              th class="px-6 py-3" scope="col" aria-label="Category and tags"
              th class="px-6 py-3" scope="col"
                span class="hover:underline" = sort_link(@q, :posts_count, "Replies")
              th class="px-6 py-3" scope="col"
                span class="hover:underline" = sort_link(@q, :num_views, "Views")
              th class="px-6 py-3" scope="col"
                span class="hover:underline" = sort_link(@q, :active_at, "Activity")
          tbody id="topics" class="dark:border-gray-700" role="rowgroup"
            = render @topics
      - else
        div class="dark:text-gray-300" role="status" aria-live="polite" No topics available.
      = turbo_frame_tag :pagination, loading: :lazy, src: forum_topics_path(format: :turbo_stream, category: params[:category], tag: params[:tag], q: @ransack_params)

app/views/forum/topics/index.turbo_stream.slim
= turbo_stream.append "topics" do
  = render @topics

= turbo_stream.append "topics" do
  - if @pagy.next.present?
    = turbo_frame_tag :pagination, loading: :lazy, src: forum_topics_path(page: @pagy.next, format: :turbo_stream, category: params[:category], tag: params[:tag], q: @ransack_params), page: @pagy.next

app/views/forum/topics/new.html.slim
div class="container mx-auto p-6"
  h1 class="text-center text-xl font-bold mb-6" Create a new Topic
  = render 'forum/topics/topic_form', form_method: :post, button_text: 'Create'

app/views/forum/topics/show.html.slim
div class="container mx-auto p-6" role="main" aria-label="Topic details page"
  h1 class="text-2xl font-bold dark:text-white" = @topic.title
  div class="flex items-center space-x-2 mb-4" role="region" aria-label="Topic metadata"
    div style="width: 12px; height: 12px; background-color: #{@topic.category.bg_color};" aria-hidden="true"
    h3 = link_to @topic.category.name, forum_topics_path(category: @topic.category.slug), data: { turbo: false }, class: "hover:underline dark:text-gray-200", "aria-label" => "View topics in category: #{@topic.category.name}"
    - if @topic_tags.any?
        div class="ml-2 flex flex-wrap text-gray-500 dark:text-gray-400 text-[11px]" role="list" aria-label="Topic tags"
          - @topic_tags.each_with_index do |tag, index|
            span class="dark:text-gray-400" role="listitem"= tag.name
            - if index < @topic.tags.size - 1
              span class="text-gray-500 dark:text-gray-400 mr-1" aria-hidden="true" ,
  div class="border-2 border-sky-800 dark:border-sky-700 rounded-md p-4 mb-6 dark:bg-gray-800" role="article" aria-label="Topic content"
    div class="flex space-x-2"
      - if user_linkable?(@topic.user)
        = link_to user_path(@topic.user), data: { turbo: false }, class: "cursor-pointer hover:z-10 transition-transform transform hover:scale-110", "aria-label" => "View #{user_display_name(@topic.user)}'s profile" do
          = render Shared::AvatarComponent.new(username: user_display_name(@topic.user), bg_color: @topic.user.avatar_bg_color)
      - else
        = render Shared::AvatarComponent.new(username: user_display_name(@topic.user), bg_color: @topic.user.avatar_bg_color)
      div class="flex flex-col"
        p class="font-bold #{user_text_color_classes(@topic.user)}"
          - if user_linkable?(@topic.user)
            = link_to user_path(@topic.user), data: { turbo: false }, class: "cursor-pointer hover:underline", "aria-label" => "View #{user_display_name(@topic.user)}'s profile" do
              = user_display_name(@topic.user)
          - else
            span = user_display_name(@topic.user)
        p class="mt-2 text-sm text-gray-500 dark:text-gray-400 flex items-center"
          span class="material-icons mr-1 dark:text-gray-400" aria-hidden="true"
            | schedule
          = "#{time_ago_in_words(@topic.created_at)} ago"
    div class="prose dark:prose-invert mt-4 text-gray dark:text-gray-200" 
      = render_markdown(@topic.content)
    - if current_user&.has_role?(:admin) || current_user&.has_role?(:moderator)
      div class="mt-2 flex space-x-2" role="group" aria-label="Moderator actions"
        = link_to "edit", edit_forum_topic_path(@topic), class: "hover:text-blue-500 dark:text-blue-400 dark:hover:text-blue-300 hover:underline", "aria-label" => "Edit this topic"
        = link_to "delete", forum_topic_path(@topic), method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, class: "hover:text-blue-500 dark:text-blue-400 dark:hover:text-blue-300 hover:underline", "aria-label" => "Delete this topic"
      div class="mt-2"
        - if @topic.pinned?
          div class="flex items-center space-x-1"
            span class="text-sm material-icons dark:text-gray-300" aria-hidden="true" push_pin
            = link_to update_pinned_forum_topic_path(@topic, pin: "false"), data: { "turbo-method": :patch }, class: "hover:text-blue-500 dark:text-blue-400 dark:hover:text-blue-300 hover:underline", "aria-label" => "Unpin this topic" do
              span Unpin topic
        - else
          div class="flex items-center space-x-1"
            span class="text-sm material-icons dark:text-gray-300" aria-hidden="true" push_pin
            = link_to update_pinned_forum_topic_path(@topic, pin: "true"), data: { "turbo-method": :patch }, class: "hover:text-blue-500 dark:text-blue-400 dark:hover:text-blue-300 hover:underline", "aria-label" => "Pin this topic" do
              span Pin topic
  div class="mt-6" role="region" aria-label="Topic posts"
    = render partial: "forum/posts/post", collection: @posts, as: :post
  div class="mt-6"
    = render "forum/posts/post_form", post: @post, topic: @topic