config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: "users/confirmations"
  }

  root "pages#home"

  namespace :forum do
    resources :categories, only: %i[index create update destroy show] do
      collection do
        post :index
      end
      resources :topics, only: %i[create destroy]
    end

    resources :topics do
      patch :update_pinned, on: :member
      resources :posts, only: %i[create edit update destroy]
    end

    resources :tags, only: %i[index]
  end

  resource :profile, only: %i[show edit update], controller: "users/profiles" do
    collection do
      get :change_password, action: :edit_password
      patch :update_password
      delete :soft_delete
    end
  end
  resources :users, only: %i[show], controller: "users/profiles"

  get "about", to: "pages#about"
  get "faq", to: "pages#faq"
  get "privacy-policy", to: "pages#privacy_policy"
  get "up" => "rails/health#show", as: :rails_health_check

  get "/robots.txt" => "robots#show", defaults: { format: "txt" }

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
end

app/views/layouts/_favicons.html.slim
= favicon_link_tag("apple-touch-icon.png", rel: "apple-touch-icon", type: "image/png", sizes: "180x180")
= favicon_link_tag("favicon-16x16.png", sizes: "16x16", type: "image/png")
= favicon_link_tag("favicon-32x32.png", sizes: "32x32", type: "image/png")
= favicon_link_tag("favicon-96x96.png", sizes: "96x96", type: "image/png")
= favicon_link_tag("favicon.svg", type: "image/svg+xml")
= favicon_link_tag

app/views/layouts/_nav.html.slim
nav class="border-b-2 border-gray-200 dark:border-gray-700 p-4 flex items-center justify-between sticky top-0 z-10 bg-white dark:bg-gray-900" role="banner" aria-label="Main navigation"
  div class="flex items-center space-x-4"
    span class="material-icons cursor-pointer select-none text-2xl font-bold flex items-center justify-center h-10 w-10 rounded-sm hover:bg-gray-200 dark:hover:bg-gray-700 hover:shadow-md transition-all dark:text-gray-200" data-action="click->sidebar#toggle" aria-label="Toggle sidebar menu" role="button" tabindex="0"
      | menu
    = link_to "discuss²", forum_topics_path, class: "font-bold text-3xl font-serif dark:text-white", style: "font-family: Georgia;", "aria-label": "discuss² home page"
  div class="flex items-center space-x-4"
    - if current_user
      div class="relative cursor-pointer select-none" data-controller="dropdown" data-action="click->dropdown#toggle" data-dropdown-should-update-arrow-icon-value="false"
        div class="flex items-center justify-center w-12 h-12 hover:bg-gray-200 dark:hover:bg-gray-700 hover:shadow-md transition-all" aria-label="User menu" role="button" tabindex="0"
          = render Shared::AvatarComponent.new(username: current_user.username, bg_color: current_user.avatar_bg_color)
        ul class="mt-1 absolute right-0 top-full w-48 bg-white dark:bg-gray-800 text-black dark:text-white shadow-lg rounded hidden border dark:border-gray-700" data-dropdown-target="menu" role="menu" aria-label="User account options"
          li class="px-4 py-2 hover:bg-gray-200 dark:hover:bg-gray-700" role="menuitem"
            = link_to "Profile", profile_path, class: "block text-left w-full", "aria-label": "View profile"
          hr class="dark:border-gray-700"
          li class="px-4 py-2 hover:bg-gray-200 dark:hover:bg-gray-700" role="menuitem"
            = button_to "Log Out", destroy_user_session_path, method: :delete, form: { "data-turbo" => "false" }, class: "block text-left w-full", "aria-label": "Log out of account"
    - else
      = link_to new_user_session_path, class: "btn btn-secondary", "aria-label": "Log in to account" do
        span class="material-icons text-base pr-1"
          | person
        span
          | Log In

app/views/layouts/_sidebar.html.slim
aside data-controller="scroll-preservation" data-action="turbo:before-cache@document->scroll-preservation#preserveScroll turbo:render@document->scroll-preservation#restoreScroll" class="flex flex-col h-[calc(100vh-3.75rem)] lg:h-[calc(100vh-5rem)] w-64 p-5 shadow-md bg-white dark:bg-gray-900 z-50 lg:z-0 fixed lg:sticky top-16 lg:top-20" role="navigation" aria-label="Sidebar navigation"
  div id="sidebar-scroll" data-scroll-preservation-target="scrollable" class="flex-grow pr-1 overflow-y-auto custom-scroll"
    ul class="space-y-4 text-sm dark:text-gray-200" role="list" aria-label="Navigation menu"
      li class="pb-4 border-b border-gray-300 dark:border-gray-700"
        = link_to forum_topics_path, class: "block px-4 py-2 rounded-lg dark:text-gray-400 #{active_link_class(forum_topics_path)} transition-all duration-300 outline-none dark:hover:bg-gray-700", "aria-label": "Topics" do
          = render "shared/icon_with_text", icon: "topic", text: "Topics"
      li class="pb-4 border-b border-gray-300 dark:border-gray-700"
        div data-controller="dropdown" data-dropdown-should-hide-on-outside-click-value="false" data-dropdown-should-save-state-value="true" data-dropdown-unique-key-value="sidebarCategories" data-dropdown-open-by-default-value="true"
          button type="button" class="block w-full px-4 py-2 text-left rounded-lg text-gray-700 dark:text-gray-200 hover:bg-neutral-200 dark:hover:bg-gray-700 hover:text-gray-900 dark:hover:text-white transition-all duration-300 outline-none" data-action="click->dropdown#toggle" aria-expanded="true" aria-controls="categories-menu" aria-label="Toggle categories menu"
            div class="flex items-center"
              = render "shared/icon_with_text", icon: "category", text: "Categories"
              span class="ml-2 material-icons" data-dropdown-target="arrowIcon"
                | keyboard_arrow_right
          ul class="mt-2 space-y-1 text-sm dark:text-gray-300" data-dropdown-target="menu" id="categories-menu" role="menu" aria-label="Categories"
            - sidebar_categories.each do |category|
              li class="block px-4 py-2 rounded-lg #{active_item_class(category.slug, params[:category])} transition-all duration-300 outline-none dark:hover:bg-gray-700" role="menuitem"
                = link_to forum_topics_path(category: category), "aria-label": "View topics in #{category.name} category" do
                  div class="flex items-center space-x-2"
                    div style="width: 12px; height: 12px; background-color: #{category.bg_color};"
                    div class="dark:text-gray-400" = category.name
            li class="block px-3 py-2 rounded-lg #{active_link_class(forum_categories_path)} text-gray-700 dark:text-gray-300 hover:bg-neutral-200 dark:hover:bg-gray-700 hover:text-gray-900 dark:hover:text-white transition-all duration-300 outline-none" role="menuitem"
              = link_to forum_categories_path, "aria-label": "View all categories" do
                = render "shared/icon_with_text", icon: "menu", text: "All Categories"
      li class="pb-4 border-b border-gray-300 dark:border-gray-700"
        div data-controller="dropdown" data-dropdown-should-hide-on-outside-click-value="false" data-dropdown-should-save-state-value="true" data-dropdown-unique-key-value="sidebarTags" data-dropdown-open-by-default-value="true"
          button type="button" class="block w-full px-4 py-2 text-left rounded-lg text-gray-700 dark:text-gray-200 hover:bg-neutral-200 dark:hover:bg-gray-700 hover:text-gray-900 dark:hover:text-white transition-all duration-300 outline-none" data-action="click->dropdown#toggle" aria-expanded="true" aria-controls="tags-menu" aria-label="Toggle tags menu"
            div class="flex items-center"
              = render "shared/icon_with_text", icon: "tag", text: "Tags"
              span class="ml-2 material-icons" data-dropdown-target="arrowIcon"
                | keyboard_arrow_right
          ul class="mt-2 space-y-1 text-sm dark:text-gray-300" data-dropdown-target="menu" id="tags-menu" role="menu" aria-label="Tags"
            - sidebar_tags.each do |tag|
              li class="block px-4 py-2 rounded-lg #{active_item_class(tag.slug, params[:tag])} transition-all duration-300 outline-none dark:hover:bg-gray-700" role="menuitem"
                = link_to forum_topics_path(tag: tag), "aria-label": "View topics tagged with #{tag.name}" do
                  div class="flex items-center space-x-2"
                    span class="material-icons text-base" sell
                    span class="dark:text-gray-400" = tag.name
            li class="block px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 #{active_link_class(forum_tags_path)} hover:bg-neutral-200 dark:hover:bg-gray-700 hover:text-gray-900 dark:hover:text-white transition-all duration-300 outline-none" role="menuitem"
              = link_to forum_tags_path, "aria-label": "View all tags" do
                = render "shared/icon_with_text", icon: "menu", text: "All Tags"
      li
        = link_to about_path, class: "block px-4 py-2 rounded-lg dark:text-gray-400 #{active_link_class(about_path)} transition-all duration-300 outline-none dark:hover:bg-gray-700", "aria-label": "About page" do
          = render "shared/icon_with_text", icon: "info", text: "About"
      li
        = link_to faq_path, class: "block px-4 py-2 rounded-lg dark:text-gray-400 #{active_link_class(faq_path)} transition-all duration-300 outline-none dark:hover:bg-gray-700", "aria-label": "Frequently asked questions" do
          = render "shared/icon_with_text", icon: "help", text: "FAQ"
  footer data-controller="theme" class="mt-4 border-t border-gray-300 dark:border-gray-700 flex justify-end" role="contentinfo" aria-label="Theme controls"
    button type="button" class="hover:bg-neutral-200 dark:hover:bg-gray-700 px-3 py-2 rounded-sm" data-action="theme#toggle" aria-label="Toggle light and dark theme"
      span class="material-icons text-sm dark:text-gray-400" data-theme-target="icon"
        | light_mode

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title = content_for(:title) || "discuss²"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = render_meta_tags
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    = render "layouts/favicons"
    link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"
    link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
    = render "shared/google_tag_manager_head"
  body data-controller="sidebar" class="bg-white dark:bg-gray-900 flex flex-col max-w-[1800px] mx-auto"
    = render "shared/flash_messages"
    = render "shared/google_tag_manager_body"
    = render "layouts/nav"
    div class="flex-grow"
      div class="flex"
        div data-sidebar-target="sidebar"
          = render "layouts/sidebar"
        main class=" dark:text-white flex-grow overflow-x-auto" aria-label="Main content area"
          = yield
		= render "shared/cookie_banner"

app/views/layouts/auth.html.slim
doctype html
html lang="en"
  head
    title = content_for(:title) || "discuss²"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = render_meta_tags
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    = render "layouts/favicons"
    link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
    = render "shared/google_tag_manager_head"
	body class="bg-white dark:bg-gray-900" data-controller="theme"
		= render "shared/flash_messages"
    = render "shared/google_tag_manager_body"
    header role="banner" class="mt-8 flex justify-center items-center"
      = link_to "discuss²", forum_topics_path, class: "font-bold text-5xl font-serif dark:text-white", style: "font-family: Georgia;", "aria-label": "Site logo"
    main role="main"
      = yield
    = render "shared/cookie_banner"

app/views/layouts/errors.html.slim
doctype html
html
  head
    title = content_for(:title) || "discuss²"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = render_meta_tags
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    = render "layouts/favicons"
    link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
  body class="bg-white dark:bg-gray-900" data-controller="theme"
		= yield
		= render "shared/cookie_banner"